[[redirects]]
  from = "/admin"
  to = "/admin/dashboard.html"
  status = 200

[[redirects]]
  from = "/customer"
  to = "/customer/dashboard.html"
  status = 200

[[redirects]]
  from = "/worker"
  to = "/worker/dashboard.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
